name: Bots CI

on:
  push

jobs:
  test:
    name: "Unit test"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod tidy
      - name: Test with Go
        run: go test ./... -short -json > test-results.json
        env:
          PORT: 8400
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: test-results.json
  deploy:
    name: "Deploy bots service"
    needs: "test"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ env.PROJECT_DIR }}
            docker compose -f deployment/docker-compose.prod.yaml down
            git stash
            git checkout main
            git pull origin main
            docker compose --env-file=.env -f deployment/docker-compose.prod.yaml up --build -d
